
Thanh Hóa:
  Thanh Hóa
  Thanh Hoa
  Thanhhoa

Ninh Bình:
  Ninh Bình
  Ninh Binh
  Ninhbinh

Nam Định:
  Nam Định
  Nam Dinh
  Namdinh

Hà Nam:
  Hà Nam
  Ha Nam
  Hanam

Thái Bình:
  Thái Bình
  Thai Binh
  Thaibinh

Hà Nội:
  Hà Nội
  Ha Noi
  Hanoi

Hưng Yên:
  Hưng Yên
  Hung Yen
  Hungyen

Hải Dương:
  Hải Dương
  Hai Duong
  Haiduong

Hải Phòng:
  Hải Phòng
  Hai Phong
  Haiphong

Quảng Ninh:
  Quảng Ninh
  Quang Ninh
  Quangninh

Bắc Ninh:
  Bắc Ninh
  Bac Ninh
  Bacninh

Bắc Giang:
  Bắc Giang
  Bac Giang
  Bacgiang

Vĩnh Phúc:
  Vĩnh Phúc
  Vinh Phuc
  Vinhphuc

Phú Thọ:
  Phú Thọ
  Phu Tho
  Phutho

Thái Nguyên:
  Thái Nguyên
  Thai Nguyen
  Thainguyen

Hòa Bình:
  Hòa Bình
  Hoa Binh
  Hoabinh